### ISSUE TITLE
Display issues: Toast is too large, then flashes at the top during animation

### ISSUE THREAD

**Issue by kf6nux** [PolymerElements/paper-toast#71]
### Description
The `paper-toast` element occasionally gets CSS element style `top: 0px`.

Subsequent invocations of `paper-toast`'s method `.show()` cause the toast animation to start from the top of the page.  After the animation completes, the toast displays properly at the bottom of the page.

### Expected outcome
The `paper-toast` element should by default display in the lower-left portion of the screen without expanding to the top of the screen.

The `paper-toast` element's animation behavior should not change permanently depending on when its `.show()` method is first invoked.

### Actual outcome
The `paper-toast` element fills the page top to bottom.

The `paper-toast` element animates at the top of the page before finishing at the bottom.

### Live Demo
https://jsbin.com/rudodozawa/edit?html,console,output

### Steps to reproduce
Call .show() method on `paper-toast` as Polymer is actively importing elements with `Polymer.Base.importHref()` while Page.js is changing what's displayed in `iron-pages`

### Work-around code
Add 
`this.style.position = "";`
`this.style.top = "";`
to `paper-toast`'s methods:
`.center()`
https://jsbin.com/vorufazace/1/edit?html,output

### Browsers Affected

- [x] Chrome
- [ ] Firefox // untested
- [ ] Safari 9 // reported unaffected
- [ ] Safari 8 // untested
- [ ] Safari 7 // untested
- [ ] Edge // tested unaffected
- [ ] IE 11 // untested
- [ ] IE 10 // untested

**Comment by kf6nux** [comment]
I found a way to recreate it in jsbin: https://jsbin.com/rudodozawa/edit?html,console,output

**Comment by ktiedt** [comment]
Some further input, the paper-toast ends up getting a `style.top = 0;` (and a few other attributes set) unfortunately I wasn't able to see what caused them in any related code... However putting the .show() behind an async... is a simple work around to this for now.

(in the jsbin)
```
      document.querySelector('paper-toast').async(function() {
        this.show('foobar');
      },1);
```

I believe this may be related to: https://bugs.chromium.org/p/chromium/issues/detail?id=564758
Reasoning: it doesn't happen in Safari

**Comment by kf6nux** [comment]
Thanks @ktiedt ! :+1:   Also, I forgot to mention, this bug has a permanent after-affect on the paper-toast element (as seen here: https://jsbin.com/loyesacevu/edit?html,console,output )

**Comment by ktiedt** [comment]
For completeness, this what I found last night:

I dug into that `paper-toast` but some more, it seems that in certain circumstances `getComputedStyles` returns different data for an element depending on that import happening and that causes `iron-fit-behavior`'s `_deviceInfo` method to cache illogical values (`top:0` and `position:static`) that these problems.

overriding `_deviceInfo` may seem like a logical fix, but even that did consistently fix things, although it did fix the after-effect from becoming permanent.

It really seems like `_deviceInfo` needs to be able to be reliably made async in order to avoid this odd glitch in Chrome.

**Comment by valdrinkoshi** [comment]
seems like a bug with how `iron-fit-behavior` gets used, probably `paper-toast` should override `resetFit` and ensure `bottom/left` is set.

**Comment by kf6nux** [comment]
Adding `this.style.position = ""; this.style.top = "";` to the end of .center() fixes the display issue.  I'm not sure if that overrides other intended behavior though.  Here's a fiddle: https://jsbin.com/vorufazace/1/edit?html,output

**Comment by ktiedt** [comment]
That may be the simplest fix and considering the comment above that method regarding IronFitBehavior, I think it may be the correct one.

**Comment by valdrinkoshi** [comment]
I noticed this happens also with a normal `div` if we try to compute its `getBoundingClientRect` https://jsbin.com/bireduh/2/edit?html,console,output

**Comment by valdrinkoshi** [comment]
You can make the `importHref` async https://jsbin.com/hofasoc/1/edit?html,console,output
```javascript 
Polymer.Base.importHref('either/good/or/bad/import.html', null, null, true);

**Comment by valdrinkoshi** [comment]
This seems an issue with imports on chrome, see this other example https://jsbin.com/necapa/2/edit?html,console,output

Reported the issue here https://bugs.chromium.org/p/chromium/issues/detail?id=629236

There has been a similar issue reported here https://github.com/Polymer/polymer/issues/3113

Closing this as it's a browser issue, and there is a proposed fix https://github.com/PolymerElements/paper-toast/issues/71#issuecomment-233433799
