### ISSUE TITLE
The `paper-toast` element is hidden from drawer content on iPad with Safari

### ISSUE THREAD

**Issue by WTober** [PolymerElements/paper-toast#77]
### Description
The `paper-toast` element is hidden from drawer content on iPad with Safari. I used PSK1.3 for my application

### Expected outcome

All other browers (including Safari on Mac) show the `paper-toast` element and the text completely over the menue (drawer content)
Video  Mac OSX 10.11  Safari 9
https://app.crossbrowsertesting.com/public/i09702162beb1f63/livetests/5326203/videos/z5d9ad4a7016b91a9b93

### Live Demo

Video from a  iPad Pro / 9.3 Simulator (that happens also on a real device)

https://app.crossbrowsertesting.com/livetests/5325596/videos/z2afd32477be1ee13a18

### Browsers Affected

- [X]  iPad Pro / 9.3 Simulator  Mobile Safari 9.0

**Comment by valdrinkoshi** [comment]
Hi @WTober, 
This is caused by the way stacking contexts work, and is a [known limitation of `iron-overlay-behavior`](https://elements.polymer-project.org/elements/iron-overlay-behavior).
It affects all overlays, e.g. see this [other issue reported on `paper-dialog`](https://github.com/PolymerElements/paper-dialog/issues/44), in particular [this comment](https://github.com/PolymerElements/paper-dialog/issues/44#issuecomment-172013206) provides more details about the cause. To work around this issue, the user is required to place overlays in a stacking-context safe node (e.g. `document.body`).

**Comment by WTober** [comment]
> To work around this issue, the user is required to place overlays in a stacking-context safe node (e.g. document.body).

Ok, at the moment I have no idea how I place overlays in a stacking-context safe node, but I try to find out.

**Comment by valdrinkoshi** [comment]
Hope this helps:
```html
<body>
  <!-- this toast is in the stacking context of body -->
  <paper-toast> </paper-toast>

  <!-- this div creates its own stacking context --> 
  <div style="transform: translateZ(0)">
    <!-- this toast is in the stacking context of the div it is contained -->
    <paper-toast></paper-toast>
  </div>
```

**Comment by valdrinkoshi** [comment]
Closing this, as it seems like a mis-use of `paper-toast`, will re-open if I'm mistaken :)
@WTober from the video you shared I cannot see the error reproduced, also the 2nd link is a 404 not found. If the problem persists, could you share a jsbin? here an example http://jsbin.com/xequvap/1/edit?html,output
