### ISSUE TITLE
<paper-toast> is partially hidden by app-drawer

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/paper-toast#80]
Hi,

This is the typical structure of an app created with polymer-cli:

    <app-drawer-layout fullbleed>

      
      <app-drawer>
        <app-toolbar>Menu</app-toolbar>

        <paper-menu selected="[[page]]" attr-for-selected="name">
          <paper-item name="view1"><a class="item fit" href="/view1">View One</a></paper-item>
          <paper-item name="view2"><a class="item fit" href="/view2">View Two</a></paper-item>
          <paper-item name="view3"><a class="item fit" href="/view3">View Three</a></paper-item>
        </paper-menu>
      </app-drawer>

      
      <app-header-layout has-scrolling-region>

        <app-header condenses reveals effects="waterfall">
          <app-toolbar>
            <paper-icon-button icon="menu" drawer-toggle></paper-icon-button>
            <div title>My App</div>
          </app-toolbar>
        </app-header>

        <iron-pages role="main" selected="[[page]]" attr-for-selected="name">
          <my-view1 name="view1"></my-view1>
          <my-view2 name="view2"></my-view2>
          <my-view3 name="view3"></my-view3>
        </iron-pages>

      </app-header-layout>

    </app-drawer-layout>

If my-view1 has a `<paper-toast>`, the toast will be partially covered by `<app-drawer>`.

This has come up before, but with the old paper-drawer widgets.

At the moment, I am "solving" this by creating a toast right in index.html and using that one application-wide. However, it would be better to find a "real" solution... Any hints?

**Comment by valdrinkoshi** [comment]
Hi @mercmobily, what you're currently doing (putting the toast on body) is the right way to have the toast on top of everything.
The issue you're facing is caused by the way stacking context works: each overlay will be "trapped" into a parent's stacking context; in your case the drawer creates a stacking context that stays on top of the main content stacking context (which traps within it its content).
You can find more info in this related issue https://github.com/PolymerElements/paper-dialog/issues/44#issuecomment-172013206.

**Comment by mercmobily** [comment]
OK thanks...! So, paper-toast and modal dialogues should always be in `<body>` -- noted!

**Comment by jpink** [comment]
And when `<paper-toast id="toast"></paper-toast>` is in `<body>` how can i get a reference to it inside a view?

Tried `document.getElementById("toast").show('Where are you?')`, but got "Uncaught TypeError: Cannot read property 'show' of null".

**Comment by aeon3k** [comment]
@jpink  did you find a solution ? I'm interested

**Comment by jpink** [comment]
I got it working, but doesn't exactly remember how.

Anyway in custom-element the `this.$.toast.show("doesn't work")` but `document.getElementById('toast').show('Works, if you call it after the element is attached to the document.')`.

**Comment by dotdoom** [comment]
@valdrinkoshi is it possible to use something similar to what https://github.com/PolymerElements/iron-overlay-behavior/pull/86 does for dialogs?

Otherwise makes sense to add some explanation to the doc, e.g. "using `paper-toast` with `app-header-layout` requires toast to be on `<body>`, available via `getElementById()`". Happy to send PR for that.

**Comment by renfeng** [comment]
An element should not depend on another one that is not its child. In other words, getElementById() defeats the idea of web components.

A better solution is to use the property, fitInto. The drawback is that you'll have to control the height and width of the container.
https://www.webcomponents.org/element/PolymerElements/paper-toast/elements/paper-toast#property-fitInto

**Comment by dotdoom** [comment]
@renfeng this sounds great. Do you have a working example with `fitInto` that works for the toast?

**Comment by renfeng** [comment]
@dotdoom This should demonstrate the problem, and the idea of using fitInto, https://github.com/renfeng/paper-toast-issue-80

**Comment by dotdoom** [comment]
@renfeng thanks (that's a great demo btw!), I understand what you mean now.

With this solution however, the toast appears inside the main container, instead of being above both the drawer and iron-pages. What I wanted is for toast to appear above all the elements on the page.

There are basically 3 UX problems that I see:

1. The toast hides immediately when switching pages. In a scenario when the user starts a long-running (seconds) operation and switches to another page, the user won't see the feedback (toast)

1. The toast is truncated on mobile devices if a drawer is opened, since a drawer may take way more than 50% of the screen

1. Subjectively, the toast attracts less attention, since it spans from a sub-component rather than the edge of the screen

Should we make an exception to the "idea of web components" for a global thing like toast?

**Comment by renfeng** [comment]
Agreed - a new toast will auto close a previous one.

Toasts should be global, in other words, be placed in the top level as @valdrinkoshi said before.

A custom event can help us to keep the idea of web components.

**Comment by renfeng** [comment]
Updated the demo with a global toast driven by customer events.

https://github.com/renfeng/paper-toast-issue-80/commit/60eb9a4314580ef13943ef1e6add27212ff7302b
